function [fcn_network] = fcn_network(training_data, training_label,label_size)

%defind network architecture
fcn_layers = [...
    imageInputLayer([1600 6 1])
    fullyConnectedLayer(200);
    reluLayer; 
    fullyConnectedLayer(200); 
    reluLayer; 
    fullyConnectedLayer(label_size);
    softmaxLayer; 
    classificationLayer]; 

%%define the options
options = trainingOptions('adam',...
    'InitialLearnRate', 1e-3,...
    'LearnRateSchedule','piecewise',...
    'LearnRateDropFactor',0.1, ...
    'LearnRateDropPeriod',5, ...
    'MaxEpochs',100, ...
    'MiniBatchSize', 24,...
    'Shuffle','every-epoch', ...
    'L2Regularization',1e-5,...
    'Plots','training-progress');

%train the network
fcn_network = trainNetwork(training_data, training_label, fcn_layers, options);



